export interface customers{
    id?: number,
    nombres?: string,
    apellidos?: string,
    tipo?: number,
    estado?: number,
    ciudad_id?: number,
    tipo_documento_id?: number,
    numero_documento?: string,
    genero_id?: number,
    estado_civil_id?: number,
    barrio_residencia?: string,
    fecha_nacimiento?: string,
    telefono?: string,
    celular?: string,
    nivel_studio_id?: number,
    correo?: string,
    observacion?: string,
    usuario_create_id?: number,
    usuario_update_id?: number,
    hotel_id?: number,
    created_at?: null,
    updated_at?: null
}